SQLITE_REV        ?= 3.39.1
SQLITE_INSTALL    := ${INSTALL_DIR}/sqlite/${SQLITE_REV}
SQLITE_DIR        := ${DOWNLOAD_DIR}/sqlite-${SQLITE_REV}

sqlite_clean:
	rm -rf $(SQLITE_INSTALL)

sqlite: mkdir_install gcc tcl | $(SQLITE_INSTALL)

$(SQLITE_DIR):
	@echo "Folder $(SQLITE_DIR) does not exist"
	rm -rf sqlite*
	wget --no-check-certificate https://www.sqlite.org/src/tarball/sqlite.tar.gz
	tar -zxvf sqlite.tar.gz
	mv sqlite ${SQLITE_DIR}

$(SQLITE_INSTALL):| $(SQLITE_DIR)
	@echo "Folder $(SQLITE_INSTALL) does not exist"
	cd ${SQLITE_DIR}; \
		export PATH=$(TCL_INSTALL)/bin:${PATH}; \
	    mkdir build; \
		cd build; \
			../configure --prefix=${SQLITE_INSTALL} --disable-tcl; \
			make; \
			make sqlite3.c; \
 			make install
