name: Test Install of bash

on: 
  push: 
  pull_request:
#   schedule:
#     - cron: '0 1 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  setup_environment:
    strategy:
      fail-fast: false # So that one fail doesn't stop remaining tests
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Bash defaults to system first
        run: |
          make bash report_paths
      - name: Add to Environment Variables
        run: |
          GITHUB_INSTALL_DIR=`make bash_install`
          echo "${GITHUB_INSTALL_DIR}/bin" >> $GITHUB_PATH
          echo "GITHUB_INSTALL_DIR=${GITHUB_INSTALL_DIR}" >> $GITHUB_ENV
      - name: Test that nothing was installed
        run: |
          FILEPATH=`which bash` 
          echo ${FILEPATH}
          if [ "/usr/bin/bash" != ${FILEPATH} ]; then
            echo "Incorrect version of exec returned";
            exit 1 ;
          fi
      - name: Make bash 
        run: |
          make bash SYSTEM_BASH=0 report_paths
      - name: Test Install Successful
        run: |
          FILEPATH=`which bash` 
          echo ${FILEPATH}
          if [ "${GITHUB_INSTALL_DIR}/bin/bash" != ${FILEPATH} ]; then
            echo "Incorrect version of exec returned";
            exit 1 ;
          fi
      - name: Remove bash 
        run: |
          make bash_clean
      - name: Test Uninstall was successful
        run: |
          FILEPATH=`which bash` 
          echo ${FILEPATH}
          if [ "/usr/bin/bash" != ${FILEPATH} ]; then
            echo "Incorrect version of exec returned";
            exit 1 ;
          fi
      - name: Make bash (again)
        run: |
          make bash SYSTEM_BASH=0 report_paths
      - name: Test Install Successful (again)
        run: |
          FILEPATH=`which bash` 
          echo ${FILEPATH}
          if [ "${GITHUB_INSTALL_DIR}/bin/bash" != ${FILEPATH} ]; then
            echo "Incorrect version of exec returned";
            exit 1 ;
          fi
