name: Test flow

on: 
#   push: 
#   pull_request:
#   schedule:
#     - cron: '0 1 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  setup_environment:
    strategy:
      fail-fast: false # So that one fail doesn't stop remaining tests
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Make libffi
        run: |
          make libffi report_paths
      - name: Test Install
        run: |
          readlink -f ~/local/tools/libffi/3.4.2/lib/pkgconfig/libffi.pc 
      - name: Make Clean
        run: |
          make libffi_clean
      - name: Test Install
        run: |
          readlink -f ~/local/tools/libffi/3.4.2/lib/pkgconfig/libffi.pc 
        continue-on-error: true
      - name: Make libffi with custom Make
        run: |
          make libffi_clean
          make libffi SYSTEM_MAKE=0 report_paths
      - name: Test Install
        run: |
          readlink -f ~/local/tools/libffi/3.4.2/lib/pkgconfig/libffi.pc 
